<?php $helper = $this->helper('Etatvasoft\WhatsAppChat\Helper\Data');?>

<?php if ($helper->getWAStatus()) : ?>
<div id="whatsappchat">
    <a href="https://web.whatsapp.com/send?phone=<?php echo $helper->getWAPhone(); ?>&amp;text=<?php echo $helper->getWAMessage(); ?>" target="_blank" class="btn-web <?php echo $helper->getWAPosition() ?>">
        <img src="<?php echo $helper->getWAIconUrl(); ?>" alt="WhatsApp Chat">
    </a>

    <a href="https://wa.me/<?php echo $helper->getWAPhone(); ?>?text=<?php echo $helper->getWAMessage(); ?>" target="_blank" class="btn-mobile <?php echo $helper->getWAPosition() ?>">
        <img src="<?php echo $helper->getWAIconUrl(); ?>" alt="WhatsApp Chat">
    </a>
</div>

<style type="text/css">
    @media(max-width: 767px) {
        #whatsappchat .btn-web{
            display: none;
        }
    }
    @media(min-width: 768px) {
        #whatsappchat .btn-mobile{
            display: none;
        }
    }
</style>
<?php endif; ?>