<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php 
if ($block->isPossibleOnepageCheckout()) { 
?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
    </button>
<?php 
} else {
?>
    <div>
        <span><i class="fa fa-tag fa-2x" aria-hidden="true"></i></span><br>
        <span><?= __('Your total order amount is greater than your credit limit.') ?></span>
    </div>
<?php
}
?>
