<script src="https://use.fontawesome.com/7102890617.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<div id="container" class="main-col">

    <div data-role="spinner" data-component="notification_area.notification_area.columns" class="admin__data-grid-loading-mask wstheme-loading">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
    <div class="message-save">
        <div class="save-success">
            <span>Registrado com sucesso!</span>
        </div>
    </div>

    <button onclick="saveTheme()" title="Salvar" type="button" class="btn-save action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" style="">
        <span><span><span>Salvar</span></span></span>
    </button>

    <div class="admin__scope-old">
        <style>
            .section-title {
                font-size: 21px;
                font-weight: 600;
                border-bottom: 1px dotted #ddd;
                padding-bottom: 15px;
            }

            .highlighted {
                background-color: #DFF7FF !important;
            }

            .section-config .note {
                font-style: italic;
            }

            .section-config input {
                width: 100%;
                padding: 0 !important;
                border: none !important;
                height: 35px !important;
            }

            .btn-save {
                float: right;
                width: 100px
            }

            .wstheme-loading {
                height: 100% !important;
                position: fixed !important;
                display: none;
            }

            .message-save {
                z-index: 9999;
                background: rgba(255, 255, 255, 0.7);
                position: fixed;
                width: calc(100% - 44px);
                height: 100%;
                top: 0;
                left: 88px;
                display: none;
            }

            .save-success {
                font-size: 2rem;
                left: 50%;
                margin-left: -13rem;
                margin-top: -3rem;
                position: absolute;
                top: 50%;
                text-align: center;
            }

            .layout-card {
                display: inline-block;
                margin-bottom: 10px;
                padding-bottom: 5px;
            }

            .layout-cart,
            .layout-header {
                display: flex;
                margin-bottom: 10px;
                border-bottom: 1px dotted #bbb;
                padding-bottom: 5px;
            }

            .layout-card .layout-select img,
            .layout-cart .layout-select img,
            .layout-header .layout-select img {
                filter: grayscale(0%) !important;
                opacity: 0.9 !important;
            }

            .layout-card img,
            .layout-cart img,
            .layout-header img {
                filter: grayscale(100%);
                opacity: 0.3;
                border-radius: 3px;
            }

            .layout-card span:first-child,
            .layout-cart span:first-child,
            .layout-header span:first-child {
                font-size: 15px;
                font-weight: 600;
                color: #eb5202;
                margin-top: 10px;
                display: inline-block;
                width: 100%;
            }

            .layout-desc {
                font-size: 13px;
                font-weight: 500;
                color: #444;
                margin: 4px 0;
                display: inline-block;
                width: 100%;
            }

            .layout-card .checkbox,
            .layout-cart .checkbox,
            .layout-header .checkbox {
                background: #e6e6e6;
                border: 1px solid #949494 !important;
                height: 16px !important;
                width: 16px;
            }

            .layout-cart .img,
            .layout-header .img {
                width: calc(100% - 200px);
            }

            .layout-cart .select,
            .layout-header .select {
                width: 200px;
            }

            .layout-card {
                width: 250px;
                padding: 0 10px;
            }

            .layout-card .img,
            .layout-card .select {
                width: 100%;
            }

            .layout-card .img {
                margin-top: 10px;
            }

            .layout-card .img img {
                margin: auto;
                display: block;
            }

            .layout-card .layout-desc {
                min-height: 35px;
            }
        </style>

        <div class="accordion">
            <div class="entry-edit form-inline">

                <div class="section-title">
                    <span><i class="fa fa-th" aria-hidden="true"></i> <?= __('Layout Manager') ?></span>
                </div>

                <script>
                    function choiceLayout(item) {
                        jQuery(item).parent().parent().parent().find('.layout').each(function(index) {
                            jQuery(this).find('.img').removeClass('layout-select');
                            jQuery(this).find('input').removeAttr('checked');
                        });

                        jQuery(item).parent().parent().find('.img').addClass('layout-select');
                        jQuery(item).parent().parent().find('input').attr("checked", "checked");
                    }
                </script>

                <div class="section-config">
                    <div class="entry-edit-head admin__collapsible-block"><span id="wstheme-layoutheader-link" class="entry-edit-head-link"></span><a id="wstheme-layoutheader-head" href="#wstheme-layoutheader-link" onclick="Fieldset.toggleCollapse('wstheme-layoutheader', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Header</a></div><input id="wstheme-layoutheader-state" name="config_state[wstheme-layoutheader]" type="hidden" value="0">
                    <fieldset class="config admin__collapsible-block" id="wstheme-layoutheader" style="display: none;">
                        <legend>Header</legend>

                        <div class="layout layout-header header-1">
                            <div class="select">
                                <span>Default v1.0</span><br>
                                <span class="layout-desc">Default header with categories inside a submenu.</span><br>
                                <input class="checkbox" id="header1" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('header') == 'header1' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('header') == 'header1' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/header1.png'); ?>">
                            </div>
                        </div>

                        <div class="layout layout-header header-2">
                            <div class="select">
                                <span>Default v2.0</span><br>
                                <span class="layout-desc">Default header with categories inside a dropdown menu.</span><br>
                                <input class="checkbox" id="header2" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('header') == 'header2' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('header') == 'header2' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/header2.png'); ?>">
                            </div>
                        </div>

                    </fieldset>
                    <script type="text/javascript">
                        //<![CDATA[
                        require(['prototype'], function() {
                            Fieldset.applyCollapse('wstheme-layoutheader');
                        });
                        //]]>                      
                    </script>
                </div>            

                <div class="section-config">
                    <div class="entry-edit-head admin__collapsible-block"><span id="wstheme-layoutcard-link" class="entry-edit-head-link"></span><a id="wstheme-layoutcard-head" href="#wstheme-layoutcard-link" onclick="Fieldset.toggleCollapse('wstheme-layoutcard', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Card</a></div><input id="wstheme-layoutcard-state" name="config_state[wstheme-layoutcard]" type="hidden" value="0">
                    <fieldset class="config admin__collapsible-block" id="wstheme-layoutcard" style="display: none;">
                        <legend>Card</legend>

                        <div class="layout layout-card card-1">
                            <div class="select">
                                <span>Default v1.0</span><br>
                                <span class="layout-desc">Default card layout.</span><br>
                                <input class="checkbox" id="card1" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('card') == 'card1' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('card') == 'card1' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/card1.png'); ?>">
                            </div>
                        </div>

                        <div class="layout layout-card card-2">
                            <div class="select">
                                <span>Default v2.0</span><br>
                                <span class="layout-desc">Default card with short description.</span><br>
                                <input class="checkbox" id="card2" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('card') == 'card2' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('card') == 'card2' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/card2.png'); ?>">
                            </div>
                        </div>

                        <div class="layout layout-card card-3">
                            <div class="select">
                                <span>Default v3.0</span><br>
                                <span class="layout-desc">Default card without button to buy.</span><br>
                                <input class="checkbox" id="card3" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('card') == 'card3' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('card') == 'card3' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/card3.png'); ?>">
                            </div>
                        </div>

                    </fieldset>
                    <script type="text/javascript">
                        //<![CDATA[
                        require(['prototype'], function() {
                            Fieldset.applyCollapse('wstheme-layoutcard');
                        });
                        //]]>                      
                    </script>
                </div>

                <div class="section-config">
                    <div class="entry-edit-head admin__collapsible-block"><span id="wstheme-layoutcart-link" class="entry-edit-head-link"></span><a id="wstheme-layoutcart-head" href="#wstheme-layoutcart-link" onclick="Fieldset.toggleCollapse('wstheme-layoutcart', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Cart Item</a></div><input id="wstheme-layoutcart-state" name="config_state[wstheme-layoutcart]" type="hidden" value="0">
                    <fieldset class="config admin__collapsible-block" id="wstheme-layoutcart" style="display: none;">
                        <legend>Cart Item</legend>

                        <div class="layout layout-cart cart-1">
                            <div class="select">
                                <span>Default v1.0</span><br>
                                <span class="layout-desc">Default cart item with menu options below.</span><br>
                                <input class="checkbox" id="cart1" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('cart') == 'cart1' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('cart') == 'cart1' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/cart1.png'); ?>">
                            </div>
                        </div>

                        <div class="layout layout-cart cart-2">
                            <div class="select">
                                <span>Default v2.0</span><br>
                                <span class="layout-desc">Default cart item with menu options on right.</span><br>
                                <input class="checkbox" id="cart2" type="checkbox" onclick="choiceLayout(this)" <?= $block->getTheme('cart') == 'cart2' ? 'checked' : '' ?>>
                                <label>Selecionar</label>
                            </div>
                            <div class="img <?= $block->getTheme('cart') == 'cart2' ? 'layout-select' : '' ?>">
                                <img src="<?php echo $block->getViewFileUrl('Wealthsystems_Mastertheme::images/cart2.png'); ?>">
                            </div>
                        </div>

                    </fieldset>
                    <script type="text/javascript">
                        //<![CDATA[
                        require(['prototype'], function() {
                            Fieldset.applyCollapse('wstheme-layoutcart');
                        });
                        //]]>                      
                    </script>
                </div>
            </div>
        </div>


        <div class="entry-edit form-inline">

            <div class="section-title">
                <span><i class="fa fa-paint-brush" aria-hidden="true"></i> <?= __('Colors Manager') ?></span>
            </div>

            <div class="section-config">
                <div class="entry-edit-head admin__collapsible-block"><span id="wsprice_general-link" class="entry-edit-head-link"></span><a id="wsprice_general-head" href="#wsprice_general-link" onclick="Fieldset.toggleCollapse('wsprice_general', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Header</a></div><input id="wsprice_general-state" name="config_state[wsprice_general]" type="hidden" value="0">
                <fieldset class="config admin__collapsible-block" id="wsprice_general" style="display: none;">
                    <legend>Header</legend>
                    <table cellspacing="0" class="form-list">
                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>
                        <colgroup class="scope-label"></colgroup>
                        <colgroup class=""></colgroup>
                        <tbody>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_background') ?>" type="color" id="header_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_text') ?>" type="color" id="header_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Cart Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_cart_background') ?>" type="color" id="header_cart_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Cart Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_cart_text') ?>" type="color" id="header_cart_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Cart Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_cart_text_hover') ?>" type="color" id="header_cart_text_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Search Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_search_background') ?>" type="color" id="header_search_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Search Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_search_text') ?>" type="color" id="header_search_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Account Menu Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_account_background') ?>" type="color" type="color" id="header_account_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Account Menu Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('header_account_text') ?>" type="color" id="header_account_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="css code only">Custom CSS</span></label></td>
                                <td class="value">
                                    <textarea rows="4" id="header_css" class="input css-option admin__control-input"><?= $block->getTheme('header_css') ?></textarea>
                                    <p class="note"><span>Insert you CSS code into header</span></p>
                                </td>
                                <td class=""></td>
                            </tr>
                        </tbody>
                    </table>
                </fieldset>
                <script type="text/javascript">
                    //<![CDATA[
                    require(['prototype'], function() {
                        Fieldset.applyCollapse('wsprice_general');
                    });
                    //]]>                      
                </script>
            </div>
            <div class="section-config">
                <div class="entry-edit-head admin__collapsible-block"><span id="wsprice_taxtable-link" class="entry-edit-head-link"></span><a id="wsprice_taxtable-head" href="#wsprice_taxtable-link" onclick="Fieldset.toggleCollapse('wsprice_taxtable', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Category Menu</a></div><input id="wsprice_taxtable-state" name="config_state[wsprice_taxtable]" type="hidden" value="0">
                <fieldset class="config admin__collapsible-block" id="wsprice_taxtable" style="display: none;">
                    <legend>Category Menu</legend>
                    <table cellspacing="0" class="form-list">
                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>
                        <colgroup class="scope-label"></colgroup>
                        <colgroup class=""></colgroup>
                        <tbody>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_background') ?>" type="color" id="menu_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Item Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_item_background') ?>" type="color" id="menu_item_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Item Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_item_text') ?>" type="color" id="menu_item_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Item Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_item_background_hover') ?>" type="color" id="menu_item_background_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Item Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_item_text_hover') ?>" type="color" id="menu_item_text_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Submenu Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_submenu_background') ?>" type="color" id="menu_submenu_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Submenu Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_submenu_text') ?>" type="color" id="menu_submenu_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Submenu Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('menu_submenu_text_hover') ?>" type="color" id="menu_submenu_text_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="CSS Code only">Custom CSS</span></label></td>
                                <td class="value">
                                    <textarea rows="4" id="menu_css" class="input css-option admin__control-input"><?= $block->getTheme('menu_css') ?></textarea>
                                    <p class="note"><span>Insert you CSS code into menu</span></p>
                                </td>
                                <td class=""></td>
                            </tr>
                        </tbody>
                    </table>
                </fieldset>
                <script type="text/javascript">
                    //<![CDATA[
                    require(['prototype'], function() {
                        Fieldset.applyCollapse('wsprice_taxtable');
                    });
                    //]]>
                </script>
            </div>
            <div class="section-config">
                <div class="entry-edit-head admin__collapsible-block"><span id="wsprice_pricetable-link" class="entry-edit-head-link"></span><a id="wsprice_pricetable-head" href="#wsprice_pricetable-link" onclick="Fieldset.toggleCollapse('wsprice_pricetable', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">Buttons</a></div><input id="wsprice_pricetable-state" name="config_state[wsprice_pricetable]" type="hidden" value="0">
                <fieldset class="config admin__collapsible-block" id="wsprice_pricetable" style="display: none;">
                    <legend>Buttons</legend>
                    <table cellspacing="0" class="form-list">
                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>
                        <colgroup class="scope-label"></colgroup>
                        <colgroup class=""></colgroup>
                        <tbody>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('button_background') ?>" type="color" id="button_background" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('button_text') ?>" type="color" id="button_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('button_background_hover') ?>" type="color" id="button_background_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('button_text_hover') ?>" type="color" id="button_text_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                        </tbody>
                    </table>
                </fieldset>
                <script type="text/javascript">
                    //<![CDATA[
                    require(['prototype'], function() {
                        Fieldset.applyCollapse('wsprice_pricetable');
                    });
                    //]]>
                </script>
            </div>
            <div class="section-config">
                <div class="entry-edit-head admin__collapsible-block"><span id="wsprice_discounttable-link" class="entry-edit-head-link"></span><a id="wsprice_discounttable-head" href="#wsprice_discounttable-link" onclick="Fieldset.toggleCollapse('wsprice_discounttable', 'http://192.168.0.111/admin/admin/system_config/state/key/db5de0081e61af3cd0eba7a02c1863f1490775744a5432ad8f7b0e2c2172bf1b/'); return false;" class="">General Content</a></div><input id="wsprice_discounttable-state" name="config_state[wsprice_discounttable]" type="hidden" value="0">
                <fieldset class="config admin__collapsible-block" id="wsprice_discounttable" style="display: none;">
                    <legend>General Content</legend>
                    <table cellspacing="0" class="form-list">
                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>
                        <colgroup class="scope-label"></colgroup>
                        <colgroup class=""></colgroup>
                        <tbody>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Text Label Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_text_color') ?>" type="color" id="content_text_color" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Text Link Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_link_color') ?>" type="color" id="content_link_color" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="mouse over">Text Link Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_link_color_hover') ?>" type="color" id="content_link_color_hover" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Icon Background Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_icon_color') ?>" type="color" id="content_icon_color" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Icon Text Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_icon_text') ?>" type="color" id="content_icon_text" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Card Name Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_card_name') ?>" type="color" id="content_card_name" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="main">Card Details Color</span></label></td>
                                <td class="value">
                                    <input value="<?= $block->getTheme('content_card_details') ?>" type="color" id="content_card_details" class="input css-option admin__control-input">
                                </td>
                                <td class=""></td>
                            </tr>
                            <tr>
                                <td class="label"><label><span data-config-scope="CSS Code only">Custom CSS</span></label></td>
                                <td class="value">
                                    <textarea rows="4" id="content_css" class="input css-option admin__control-input"><?= $block->getTheme('content_css') ?></textarea>
                                    <p class="note"><span>Insert you CSS code into content</span></p>
                                </td>
                                <td class=""></td>
                            </tr>
                        </tbody>
                    </table>
                </fieldset>
                <script type="text/javascript">
                    //<![CDATA[
                    require(['prototype'], function() {
                        Fieldset.applyCollapse('wsprice_discounttable');
                    });
                    //]]>
                </script>
            </div>
        </div>
    </div>
    <script>
        require([
            "jquery",
            "uiRegistry",
            "mage/mage",
            "prototype",
            "mage/adminhtml/form",
            "domReady!",
            "jquery/ui"
        ], function(jQuery, registry) {

            var adminSystemConfig = {
                navigateToElement: function(searchRequest) {
                    if ('section' in searchRequest) {
                        var section = searchRequest.section;
                    }
                    if ('group' in searchRequest) {
                        var group = searchRequest.group;
                    }
                    if ('field' in searchRequest) {
                        var field = searchRequest.field;
                    }
                    if (typeof section === 'undefined') {
                        return;
                    }
                    if (typeof group !== 'undefined') {
                        var groupElement = jQuery('#' + section + '_' + group);

                        var parentSection = groupElement.parents('.section-config');
                        parentSection.addClass('highlighted');
                        setTimeout(function() {
                            parentSection.removeClass('highlighted', 2000, "easeInBack");
                        }, 3000);
                        if (!parentSection.hasClass('active')) {
                            Fieldset.toggleCollapse(section + '_' + group);
                        }
                    }
                },
                getUp: function(element, tag) {
                    var $element = Element.extend(element);
                    if (typeof $element.upTag == 'undefined') {
                        $element.upTag = {};
                    }
                    if (typeof $element.upTag[tag] == 'undefined') {
                        $element.upTag[tag] = Element.extend($element.up(tag));
                    }
                    return $element.upTag[tag];
                },
                getUpTd: function(element) {
                    return this.getUp(element, 'td');
                },
                getUpTr: function(element) {
                    return this.getUp(element, 'tr');
                },
                getScopeElement: function(element) {
                    var $element = Element.extend(element);
                    if (typeof $element.scopeElement == 'undefined') {
                        var scopeElementName = element.getAttribute('name').replace(/\[value\]$/, '[inherit]');
                        $element.scopeElement = this.getUpTr(element).select('input[name="' + scopeElementName + '"]')[0];
                        if (typeof $element.scopeElement == 'undefined') {
                            $element.scopeElement = false;
                        }
                    }
                    return $element.scopeElement;
                },
                getDeleteElement: function(element) {
                    var $element = Element.extend(element);
                    if (typeof $element.deleteElement == 'undefined') {
                        $element.deleteElement = this.getUpTd(element)
                            .select('input[name="' + element.getAttribute('name') + '[delete]"]')[0];
                        if (typeof $element.deleteElement == 'undefined') {
                            $element.deleteElement = false;
                        }
                    }
                    return $element.deleteElement;
                },
                mapClasses: function(element, full, callback, classPrefix) {
                    if (typeof classPrefix == 'undefined') {
                        classPrefix = 'shared'
                    }
                    element.classNames().each(function(className) {
                        if (className.indexOf(classPrefix + '-') == 0 ||
                            (full && className.indexOf(classPrefix + '_') == 0)
                        ) {
                            callback(className);
                        }
                    });
                },
                getRegisteredEvents: function(element) {
                    var events = [];
                    var registry = Element.retrieve(Element.extend(element), 'prototype_event_registry');
                    if (!registry) {
                        return events;
                    }
                    registry.each(function(pair) {
                        var eventName = pair.key;
                        if (!eventName) {
                            return;
                        }
                        var responders = registry.get(eventName);
                        if (!responders) {
                            return;
                        }
                        responders.each(function(responder) {
                            if (!responder.handler) {
                                return;
                            }
                            events.push({
                                'eventName': eventName,
                                'handler': responder.handler
                            });
                        });
                    });
                    return events;
                },
                onchangeSharedElement: function(event) {
                    var element = Element.extend(Event.element(event));
                    adminSystemConfig.mapClasses(element, true, function(className) {
                        $$('.' + className).each(function(el) {
                            if (element == el) {
                                return;
                            }

                            var tagName = el.tagName.toLowerCase();
                            if (tagName == 'input' && el.getAttribute('type') == 'file') {
                                var $el = Element.extend(el);
                                var events = adminSystemConfig.getRegisteredEvents(el);
                                $el.stopObserving('change');
                                var elId = $el.id;
                                $el.replace($el.outerHTML);
                                events.each(function(event) {
                                    Event.observe(Element.extend(document.getElementById(elId)), event.eventName, event.handler);
                                });
                            } else {
                                el.stopObserving('change', adminSystemConfig.onchangeSharedElement);
                                if (tagName == 'input' && el.getAttribute('type') == 'checkbox') {
                                    if (el.checked != element.checked) {
                                        Element.extend(el).click();
                                    }
                                } else if (tagName == 'select') {
                                    var $el = Element.extend(el);
                                    Element.extend(element).select('option').each(function(option) {
                                        var relatedOption = $el.select('option[value="' + option.value + '"]')[0];
                                        if (typeof relatedOption != 'undefined') {
                                            relatedOption.selected = option.selected;
                                        }
                                    });
                                } else {
                                    el.value = element.getValue();
                                }
                                if (Element.extend(el).requiresObj) {
                                    Element.extend(el).requiresObj.indicateEnabled();
                                }
                                fireEvent(el, 'change');
                                Event.observe(el, 'change', adminSystemConfig.onchangeSharedElement);
                            }
                        });
                    });
                },
                checkRequired: function(element, callback) {
                    var tagName = this.tagName.toLowerCase();
                    if (tagName != 'fieldset') {
                        if (adminSystemConfig.getUpTr(this).visible()) {

                            if (this.hasClassName('not-required')) {
                                return;
                            }

                            var typeAttr = null;
                            if (tagName == 'input') {
                                typeAttr = this.getAttribute('type').toLowerCase();
                            }
                            var valueIsEmpty = false;
                            var scopeElement = adminSystemConfig.getScopeElement(this);
                            if (!scopeElement || !scopeElement.checked) {
                                if (typeAttr == 'file') {
                                    var deleteUploadedElement = adminSystemConfig.getDeleteElement(this);
                                    valueIsEmpty = !deleteUploadedElement && this.value == '' ||
                                        deleteUploadedElement && deleteUploadedElement.checked;
                                }
                                valueIsEmpty = valueIsEmpty ||
                                    (typeAttr == 'text' || typeAttr == 'password') && this.value == '' ||
                                    (tagName == 'select') && (this.getAttribute('multiple') != null) &&
                                    this.getValue().length == 0 ||
                                    (tagName == 'select') && (this.getAttribute('multiple') == null) &&
                                    this.getValue() == null;
                            }

                            if (valueIsEmpty) {
                                if (element.value != 0) {
                                    element.value = 0;
                                    fireEvent(element, 'change');
                                }
                                element.disable();
                            }
                        }
                    } else {
                        this.select('input,select').each(function(inputElement) {
                            adminSystemConfig.checkRequired.call(Element.extend(inputElement), element, callback);
                        });
                    }
                    callback(this);
                }
            };

            window.configForm = jQuery('#config-edit-form').mage('form').mage('validation', {
                submitHandler: function(form) {
                    $$('.requires').each(function(element) {
                        var scopeElement = adminSystemConfig.getScopeElement(element);
                        if (!scopeElement || !scopeElement.checked) {
                            Element.extend(element).disabled = false;
                        }
                    });
                    jQuery(form).trigger('afterValidate');
                    form.submit();
                }
            });

            $$('.shared').each(function(element) {
                Event.observe(element, 'change', adminSystemConfig.onchangeSharedElement);

                // scope should be shared together with the field
                var scopeElement = adminSystemConfig.getScopeElement(element);
                if (scopeElement) {
                    adminSystemConfig.mapClasses(element, false, function(className) {
                        scopeElement.addClassName('shared_scope-' + className.substr(7));
                    });
                    Event.observe(scopeElement, 'change', adminSystemConfig.onchangeSharedElement);
                }

                // file fields should share deletion
                if (element.tagName.toLowerCase() == 'input' && element.getAttribute('type') == 'file') {
                    var deleteUploadedElement = adminSystemConfig.getDeleteElement(element);
                    if (deleteUploadedElement) {
                        adminSystemConfig.mapClasses(element, false, function(className) {
                            deleteUploadedElement.addClassName('shared_delete-' + className.substr(7));
                        });
                        Event.observe(deleteUploadedElement, 'change', adminSystemConfig.onchangeSharedElement);
                    }
                }

                // process situation, when control is complex
                adminSystemConfig.mapClasses(element, true, function(className) {
                    var controls = adminSystemConfig.getUpTd(element).select('.' + className);
                    if (controls.length < 2) {
                        return;
                    }

                    var counter = 0;
                    controls.each(function(controlElement) {
                        controlElement.removeClassName(className);
                        controlElement.addClassName('shared_' + counter + className.substr(6));
                        counter++;
                    });
                });
            });

            $$('.requires').each(function(element) {
                var eventObj = {
                    'element': Element.extend(element),
                    'requires': [],
                    'callback': function(required) {},
                    checkRequirements: function() {
                        var scopeElement = adminSystemConfig.getScopeElement(eventObj.element);
                        if (!scopeElement || !scopeElement.checked) {
                            eventObj.element.enable();
                            eventObj.requires.each(function(required) {
                                adminSystemConfig.checkRequired.call(Element.extend(required), eventObj.element, eventObj.callback);
                            }.bind(this));
                        }
                    },
                    keydownCheckRequirements: function() {
                        window.setTimeout(eventObj.checkRequirements, 1);
                    },
                    bindCheckingObserver: function(element) {
                        if (element.tagName.toLowerCase() == 'fieldset') {
                            Element.extend(element).select('input,select').each(function(subElement) {
                                eventObj.bindCheckingObserver(subElement);
                            })
                        } else {
                            var scopeElement = adminSystemConfig.getScopeElement(element);
                            if (scopeElement) {
                                Event.observe(scopeElement, 'click', eventObj.checkRequirements);
                            }
                            Event.observe(element, 'change', eventObj.checkRequirements);
                            Event.observe(element, 'keydown', eventObj.keydownCheckRequirements);
                        }
                    },
                    indicateEnabled: function() {
                        var labelElement = adminSystemConfig.getUpTr(eventObj.element).select('td.label label')[0];
                        if (typeof labelElement != 'undefined') {
                            if (eventObj.element.value == 1) {
                                labelElement.addClassName('enabled');
                            } else {
                                labelElement.removeClassName('enabled');
                            }
                        }
                    }
                };

                // fill eventObj with required elements
                adminSystemConfig.mapClasses(element, false, function(className) {
                    var requiredElement = Element.extend(document.getElementById(className.substr(9)));
                    if (requiredElement) {
                        eventObj.requires.push(requiredElement);
                    }
                }, 'requires');
                Element.extend(element).requiresObj = eventObj;

                // replacing "Use Default" action with checking requirements
                var scopeElement = adminSystemConfig.getScopeElement(element);
                if (scopeElement) {
                    Event.stopObserving(scopeElement, 'click');
                    Event.observe(scopeElement, 'click', function(event) {
                        toggleValueElements(scopeElement, Element.previous(scopeElement.parentNode));
                        eventObj.checkRequirements();
                    });
                }

                // binding events
                eventObj.requires.each(function(required) {
                    eventObj.bindCheckingObserver(required);
                });
                Event.observe(eventObj.element, 'change', eventObj.indicateEnabled);
                eventObj.checkRequirements();
                eventObj.indicateEnabled();
            });

            var handleHash = function() {
                if (window.location.hash == '') {
                    return false;
                }
                try {
                    var hashString = window.location.hash.replace('#', ''),
                        containerId = hashString.replace('-link', ''),
                        state = jQuery('#' + containerId + '-state'),
                        head = jQuery('#' + containerId + '-head');
                    if (state.length) {
                        state.val(1);
                    }
                    if (head.length) {
                        head.collapsed = 0;
                    }
                    Fieldset.applyCollapse(containerId);
                } catch (err) {}
                return false;
            };

            window.addEventListener('hashchange', handleHash);
            handleHash();

            registry.set('adminSystemConfig', adminSystemConfig);

            adminSystemConfig.navigateToElement({
                "section": "wsprice"
            });
        });

        function saveTheme() {
            jQuery('.wstheme-loading').show();
            var level = [];

            var r_data = [];
            var r_element = [];
            var r_value = [];

            jQuery('.css-option').each(function(index) {
                r_data = [];
                r_element = [];
                r_value = [];

                r_element.push(jQuery(this).attr('id'));
                r_value.push(jQuery(this).val());

                r_data.push(r_element);
                r_data.push(r_value);

                level.push(r_data);
            });

            jQuery('.layout-header').each(function(index) {
                if (jQuery(this).find('input').attr('checked')) {
                    r_data = [];
                    r_element = [];
                    r_value = [];

                    r_element.push('header');
                    r_value.push(jQuery(this).find('input').attr('id'));

                    r_data.push(r_element);
                    r_data.push(r_value);

                    level.push(r_data);
                }
            });

            jQuery('.layout-card').each(function(index) {
                if (jQuery(this).find('input').attr('checked')) {
                    r_data = [];
                    r_element = [];
                    r_value = [];

                    r_element.push('card');
                    r_value.push(jQuery(this).find('input').attr('id'));

                    r_data.push(r_element);
                    r_data.push(r_value);

                    level.push(r_data);
                }
            });

            jQuery('.layout-cart').each(function(index) {
                if (jQuery(this).find('input').attr('checked')) {
                    r_data = [];
                    r_element = [];
                    r_value = [];

                    r_element.push('cart');
                    r_value.push(jQuery(this).find('input').attr('id'));

                    r_data.push(r_element);
                    r_data.push(r_value);

                    level.push(r_data);
                }
            });

            result = jQuery.unique(level);
            result = JSON.stringify(result);

            jQuery.post("<?= $block->getUrl("mastertheme/index/themesave"); ?>", {
                    result: result
                },
                function(data) {
                    jQuery('.message-save').show();
                    jQuery('.wstheme-loading').hide();
                    setTimeout(function() {
                        jQuery('.message-save').hide();
                    }, 3500);
                }
            )

        }
    </script>
</div>