<div class="container">

    <style>
        .item .options {
            padding: 10px;
            width: calc(50% - 170px);
        }
        .item .options div {
            width: calc(50% - 5px);
            display: inline-block;
            margin-bottom: 4px;
        }
        .item .options div input, 
        .item .options div select {
            width: calc(100% - 2px);
            padding: 6px;
            background: #f9f9f9;
            border: 1px solid #e4e4e4;
            color: #514943;
            margin-top: 4px;
        }
    </style>

    <div><input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>"></div>

    <span class="msg">*clique e arraste para ordernar as regras.</span>

    <button onclick="saveRule()" title="Salvar" type="button" class="btn-save action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" style="">
        <span><span><span>Salvar</span></span></span>
    </button>

    <div class="list-item" id="sortable">

        <?php
        $taxes = $block->getRules()->getCollection();

        if (count($taxes)) {
            foreach ($taxes as $tax) {
                ?>
                <div class="item ui-state-default">
                    <div class="options">
                        <div class="desc">
                            <span class="subtitle">Descrição</span><br>
                            <input type="text" class="desc-text" value="<?= $tax->getDescription() ?>">
                        </div>
                        <div class="code">
                            <span class="subtitle">Código</span><br>
                            <input type="text" class="code-text" value="<?= $tax->getCode() ?>">
                        </div>
                        <div class="calc">
                            <span class="subtitle">Valor para cálculo</span><br>
                            <select class="calc-type">
                                <option <?= $tax->getCalculation() == 0 ? 'selected' : '' ?> value="0">Preço Original</option>
                                <option <?= $tax->getCalculation() == 1 ? 'selected' : '' ?> value="1">Preço Atualizado</option>
                            </select>
                        </div>
                    </div>   

                    <div class="rules">
                        <div class="list-rules">
                            <div class="select-rules">
                                <span class="subtitle">Regras</span>

                                <?php
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $taxRules = $objectManager->create('Wealthsystems\Masterprice\Model\Taxrule');

                                foreach (json_decode($tax->getRules()) as $_rule){                                
                                ?>
                                <select name="variable[<?= substr(md5(microtime() . rand()), 0, 14) ?>][<?= substr(md5(microtime() . rand()), 0, 14) ?>]" class="variable" title="">
                                    <option value="" selected="selected">Selecione</option>                                    
                                    <?php
                                    $taxRulesCollection = $taxRules->getCollection();
                                    
                                    foreach ($taxRulesCollection as $_taxRule){                                
                                    ?>
                                    <option <?= $_rule == $_taxRule->getId() ? 'selected="selected"' : '' ?> value="<?= $_taxRule->getId() ?>"><?= $_taxRule->getDescription() ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                                <?php
                                }
                                ?>

                                <button onclick="removeOption(this)" class="scalable delete btn-remove  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button"><span><span><span>Remove</span></span></span></button>
                            </div>
                        </div>
                        <div class="add-rules">
                            <button onclick="addOption(this)" class="btn-add action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">
                                <span><span><span>Nova Variável</span></span></span>
                            </button>
                        </div>
                    </div>

                    <div class="option">
                        <button onclick="removeRule(this)" class="scalable delete btn-remove  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Remover Regra</button>
                        <button onclick="resetRule(this)" class="scalable reset btn-reset  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Limpar Regra</button>
                    </div>
                </div>
            <?php
                }
            } else {
            ?>            

            <div class="item ui-state-default">

                <div class="options">
                    <div class="desc">
                        <span class="subtitle">Descrição</span><br>
                        <input type="text" class="desc-text">
                    </div>
                    <div class="code">
                        <span class="subtitle">Código</span><br>
                        <input type="text" class="code-text">
                    </div>
                    <div class="calc">
                        <span class="subtitle">Valor para cálculo</span><br>
                        <select class="calc-type">
                            <option value="0">Preço Original</option>
                            <option value="1">Preço Atualizado</option>
                        </select>
                    </div>
                </div>                 

                <div class="rules">
                    <div class="list-rules">
                        <div class="select-rules">
                            <span class="subtitle">Regras</span>

                            <select name="variable[<?= substr(md5(microtime() . rand()), 0, 14) ?>][<?= substr(md5(microtime() . rand()), 0, 14) ?>]" class="variable" title="">
                                <option value="" selected="selected">Selecione</option>
                                
                                <?php
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $taxRules = $objectManager->create('Wealthsystems\Masterprice\Model\Taxrule');

                                $taxRulesCollection = $taxRules->getCollection();
                                
                                foreach ($taxRulesCollection as $_taxRule){                                
                                ?>
                                <option value="<?= $_taxRule->getId() ?>"><?= $_taxRule->getDescription() ?></option>
                                <?php
                                }
                                ?>

                            </select>

                            <button onclick="removeOption(this)" class="scalable delete btn-remove  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button"><span><span><span>Remove</span></span></span></button>
                        </div>
                    </div>
                    <div class="add-rules">
                        <button onclick="addOption(this)" class="btn-add action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">
                            <span><span><span>Nova Variável</span></span></span>
                        </button>
                    </div>
                </div>

                <div class="option">
                    <button onclick="removeRule(this)" class="scalable delete btn-remove  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Remover Regra</button>
                    <button onclick="resetRule(this)" class="scalable reset btn-reset  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Limpar Regra</button>
                </div>
            </div>

        <?php
        }
        ?>

    </div>
    <div>
        <button onclick="addRule();checkDefault();" class="btn-add action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">
            <span><span><span>Nova Regra</span></span></span>
        </button>
    </div>


    <script>
        jQuery("#sortable").sortable();

        function saveRule() {
            var level = [];

            var r_rules = [];
            var r_desc = [];
            var r_code = [];
            var r_type = [];
            var r_variables = [];

            jQuery('.item').each(function(index) {
                r_rules = [];
                r_desc = [];
                r_code = [];
                r_type = [];
                r_variables = [];

                desc = jQuery(this).find('.desc-text').val();
                r_desc.push(desc);

                code = jQuery(this).find('.code-text').val();
                r_code.push(code);

                type = jQuery(this).find('.calc-type').val();
                r_type.push(type);

                jQuery(this).find('.select-rules').each(function(index) {
                    variable = jQuery(this).find('.variable').val();
                    r_variables.push(variable);
                });

                r_rules.push(r_variables);
                r_rules.push(desc);
                r_rules.push(type);
                r_rules.push(code);

                level.push(r_rules);
            });

            result = jQuery.unique(level);
            result = JSON.stringify(result);

            jQuery.post("<?= $block->getUrl("masterprice/index/taxsave"); ?>", {
                    result: result
                },
                function(data) {
                    alert('Registrado com sucesso!');
                }
            )

        }
    </script>